---
- hosts: all
  become: yes

  vars_files:
    - default.config.yml

  roles: 
    - role: penguinperk.postfix_ansible_role
    - role: penguinperk.bind_client_ansible_role

  tasks:
  - include_tasks: tasks/zfs.yml
