# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ebarriosjr/FreeBSD12-zfs"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  #Freebsd12
  config.vm.define "freebsd12" do |s|
    s.vm.hostname = "freebsd.test"
    s.vm.network :private_network, ip: "192.168.60.4"
  end
end
